// goty-react/src/components/submission/OldGame.tsx
import { Game } from "../../models/game"
import { generateRules } from "../../util/generate-rules"
import { SingleGame } from "./shared/SingleGame"

export interface OldGameProps {
  year: number
  readonly: boolean
  bestOldGame: Game | null
  setBestOldGame: (game: Game | null) => void
}

const rules = (year: number) => [`Any game released prior to ${year}`]

export const OldGame = (props: OldGameProps) => {
  return (
    <SingleGame
      title={`What is your favorite OLD game of ${props.year}`}
      readonly={props.readonly}
      game={props.bestOldGame}
      handleSelect={props.setBestOldGame}
      content={generateRules(props.readonly, rules(props.year))}
    />
  )
}

// goty-client/src/app/form/old-game/old-game.component.ts
import {Component, Input} from '@angular/core'
import {year} from 'src/api/constants'
import {Game} from '../../../api/game.service'
import {AppService} from '../../../api/app/app.service'

@Component({
  selector: 'app-old-game',
  templateUrl: './old-game.component.html',
  styleUrls: ['./old-game.component.scss']
})
export class OldGameComponent {
  @Input() readonly = false
  @Input() bestOldGame: Game
  title = `What is your favorite OLD game of ${year}`
  year = year
  constructor(private readonly appService: AppService) {
  }

  gameSelected(bestOldGame: Game) {
    this.appService.setBestOldGame(bestOldGame)
  }
}

<app-single-game placeholder="Select a game" [game]="bestOldGame$ | async" [title]="title" (gameSelected)="gameSelected($event)">
  <ng-container rules>
    <p>What game released before {{year}} have you found yourself going back to?</p>
    <p>Rules:</p>
    <ul>
      <li>Any game released prior to {{year}}</li>
    </ul>
  </ng-container>
</app-single-game>
