// goty-client/src/app/form/most-anticipated/most-anticipated.component.ts
import {Component, Input} from '@angular/core'
import {AppService} from '../../../api/app/app.service'
import {Game} from '../../../api/game.service'

@Component({
  selector: 'app-most-anticipated',
  templateUrl: './most-anticipated.component.html',
  styleUrls: ['./most-anticipated.component.scss']
})
export class MostAnticipatedComponent {
  @Input() mostAnticipated: Game
  @Input() readonly = false
  title = 'What game are you looking forward to most?'
  constructor(private readonly appService: AppService) {
  }

  gameSelected(game: Game) {
    this.appService.setMostAnticipated(game)
  }

}

<app-single-game placeholder="Select a game" [game]="mostAnticipated$ | async" [title]="title" (gameSelected)="gameSelected($event)">
  <ng-container rules>
    <p>Rules:</p>
    <ul>
      <li>Anything not released</li>
    </ul>
  </ng-container>
</app-single-game>

// goty-react/src/components/submission/MostAnticipated.tsx
import React from 'react'
import { Game } from '../../models/game'
import { generateRules } from '../../util/generate-rules'
import { SingleGame } from './shared/SingleGame'

export interface MostAnticipatedProps {
  readonly: boolean
  mostAnticipated: Game | null
  setMostAnticipated?: (game: Game | null) => void
}

const rules: (string | JSX.Element)[] = ['Anything not released']

export const MostAnticipated = (props: MostAnticipatedProps) => {
  const handleSelect = (mostAnticipated: Game | null) => {
    if (!props.readonly && props.setMostAnticipated != null) {
      props.setMostAnticipated(mostAnticipated)
    }
  }
  return (
    <SingleGame
      title="What game are you looking forward to most?"
      readonly={props.readonly}
      game={props.mostAnticipated}
      handleSelect={handleSelect}
      content={generateRules(props.readonly, rules)}
    />
  )
}
