// goty-react/src/components/submission/shared/Search.tsx
import { Game } from '../../../models/game'
import { AutoComplete } from 'primereact/autocomplete'
import { useState } from 'react'
import { GameService } from '../../../api/gameService'

export interface SearchProps {
  placeholder: string
  year: number
  handleSelect: (game: Game) => void
}

export const Search = (props: SearchProps) => {
  const [suggestions, setSuggestions] = useState<Game[]>([])
  const handleSearch = (searchText: string) =>
    GameService.searchGames(searchText, 10, props.year).then((results) =>
      setSuggestions(results)
    )
  return (
    <AutoComplete
      completeMethod={(e) => handleSearch(e.query)}
      onSelect={(e) => props.handleSelect(e.value)}
      dropdown={true}
      inputStyle={{ width: '100%' }}
      minLength={1}
      style={{ display: 'flex', justifyContent: 'center' }}
      suggestions={suggestions}
      field="title"
      placeholder={props.placeholder}
    />
  )
}

// goty-client/src/app/form/search/search.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core'
import {Game, GameService} from '../../../api/game.service'
import {Subject} from 'rxjs'
import {switchMap} from 'rxjs/operators'

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent {
  @Input() placeholder = ''
  @Input() year: number | undefined
  @Input() limit = 10
  @Output() gameSelected = new EventEmitter<Game>()
  selectableGames: Game[]
  completeMethod = new Subject<string>()
  input = ''

  constructor(private readonly gameService: GameService) {
    this.completeMethod.asObservable().pipe(
      switchMap((searchText) => this.gameService.searchGames(searchText, 10, this.year))
    ).subscribe((selectableGames) => {
      this.selectableGames = selectableGames
    })
  }

  selectGame(game: Game) {
    this.gameSelected.emit(game)
    this.input = ''
  }

}

<p-autoComplete
  (completeMethod)="completeMethod.next($event.query)"
  (onSelect)="selectGame($event)"
  [(ngModel)]="input"
  [dropdown]="true"
  [inputStyle]="{'width':'100%'}"
  [minLength]="1"
  [style]="{'display':'flex', 'justify-content':'center', 'margin-right': '15px'}"
  [suggestions]="selectableGames"
  class="search"
  field="title"
  [placeholder]="placeholder"
></p-autoComplete>
