// goty-client/src/components/submission/MostAnticipated.tsx
import React from 'react'
import { Game } from '../../models/game'
import { SingleGame } from '../controls/SingleGame'

export interface MostAnticipatedProps {
  readonly: boolean
  mostAnticipated: Game | null
  handleSetMostAnticipated?: (game: Game | null) => void
}

const rules = ['Anything not released']

export const MostAnticipated = ({
  handleSetMostAnticipated,
  mostAnticipated,
  readonly,
}: MostAnticipatedProps) => {
  const handleSelect = (mostAnticipated: Game | null) => {
    handleSetMostAnticipated && handleSetMostAnticipated(mostAnticipated)
  }
  return (
    <SingleGame
      title="Most Anticipated"
      subtitle="What game are you looking forward to most?"
      readonly={readonly}
      game={mostAnticipated}
      handleSelect={handleSelect}
      rules={rules}
    />
  )
}

// goty-client/src/app/most-anticipated/most-anticipated.component.ts
import {Component} from '@angular/core'
import {AppService} from '../../api/app/app.service'
import {Game} from '../../api/game.service'

@Component({
  selector: 'app-most-anticipated',
  templateUrl: './most-anticipated.component.html',
  styleUrls: ['./most-anticipated.component.scss']
})
export class MostAnticipatedComponent {
  title = 'What game are you looking forward to most?'

  constructor(private readonly appService: AppService) {
  }

  gameSelected(game: Game) {
    this.appService.setMostAnticipated(game)
  }

}

<app-single-game [title]="title" (gameSelected)="gameSelected($event)">
  <ng-container rules>
    <p>Rules:</p>
    <ul>
      <li>Anything not released</li>
    </ul>
  </ng-container>
</app-single-game>
