// goty-client/src/app/submission/most-anticipated/most-anticipated.component.ts
import {Component, Input} from '@angular/core'
import {Game} from '../../../api/game.service'
import {SubmissionService} from '../../../api/submission/submission.service'

@Component({
  selector: 'app-most-anticipated',
  templateUrl: './most-anticipated.component.html',
  styleUrls: ['./most-anticipated.component.scss']
})
export class MostAnticipatedComponent {
  @Input() mostAnticipated: Game
  @Input() readonly = false
  title = 'What game are you looking forward to most?'
  constructor(private readonly submissionService: SubmissionService) {
  }

  gameSelected(game: Game) {
    this.submissionService.setMostAnticipated(game)
  }

}

<app-single-game placeholder="Select a game" [game]="mostAnticipated" [title]="title" (gameSelected)="gameSelected($event)" [readonly]="readonly">
  <ng-container *ngIf="!readonly" rules>
    <p>Rules:</p>
    <ul>
      <li>Anything not released</li>
    </ul>
  </ng-container>
</app-single-game>

// goty-client/src/components/submission/MostAnticipated.tsx
import { Game } from '../../models/game'
import { SingleGame } from '../controls/SingleGame'
import { InputStateKeyContext } from './useSubmissionForm'

export interface MostAnticipatedProps {
  readonly: boolean
  mostAnticipated: Game | null
  handleSetMostAnticipated?: (game: Game | null) => void
}

const rules = ['Anything not released']

export const MostAnticipated = ({
  handleSetMostAnticipated,
  mostAnticipated,
  readonly,
}: MostAnticipatedProps) => {
  const handleSelect = (mostAnticipated: Game | null) => {
    handleSetMostAnticipated && handleSetMostAnticipated(mostAnticipated)
  }
  return (
    <InputStateKeyContext.Provider value={'mostAnticipated'}>
      <SingleGame
        title="Most Anticipated"
        subtitle="What game are you looking forward to most?"
        readonly={readonly}
        game={mostAnticipated}
        handleSelect={handleSelect}
        rules={rules}
        placeholder="Select most anticipated game"
      />
    </InputStateKeyContext.Provider>
  )
}
