// goty-react/src/components/Title.tsx
import React from "react"
import styled from "styled-components"
import { Card } from "./Card"

const MainTitle = styled.h1`
  font-size: 2em;
  font-weight: bold;
`

const Footer = styled.div`
  margin-top: 40px;
  display: flex;
  justify-content: space-between;

  a {
    font-size: 0.8em;
    color: gray;
    text-decoration: none;
  }

  a:hover {
    color: white;
  }
`
export const Title = (props: { year: number }) => {
  const content = (
    <React.Fragment>
      <MainTitle>The Midnight Watchmen's</MainTitle>
      <MainTitle>Top Games of the Year {props.year}</MainTitle>
      <Footer>
        <a href="https://github.com/aleinin">Frontend by aleinin</a>
        <a href="https://www.igdb.com">Data provided by IGDB</a>
        <a href="https://github.com/Gorlah">Backend by Gorlah</a>
      </Footer>
    </React.Fragment>
  )
  return <Card title="" content={content} paddingPx={20}></Card>
}

// goty-client/src/app/submission/title/title.component.ts
import {Component} from '@angular/core'
import {constants} from 'src/api/constants'

@Component({
  selector: 'app-title',
  templateUrl: './title.component.html',
  styleUrls: ['./title.component.scss']
})
export class TitleComponent {
  year = constants.year
}

<div class="list-item">
  <h1 class="title">The Midnight Watchmen's</h1>
  <h1 class="title">Top Games of the Year {{year}}</h1>
  <div class="footer">
    <a href="https://github.com/aleinin">Frontend by aleinin</a>
    <a href="https://www.igdb.com">Data provided by IGDB</a>
    <a href="https://github.com/Gorlah">Backend by Gorlah</a>
  </div>
</div>
