// goty-client/src/app/recovery/recovery.component.ts
import {Component} from '@angular/core'
import {FormBuilder, Validators} from '@angular/forms'
import {SubmissionService} from '../../api/submission.service'
import {first, tap} from 'rxjs/operators'
import {genericErrorHandler} from '../../api/api-config'
import {Router} from '@angular/router'
import {UIService} from '../../api/ui/ui.service'

const uuidPattern = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/

@Component({
  selector: 'app-recovery',
  templateUrl: './recovery.component.html',
  styleUrls: ['./recovery.component.scss']
})
export class RecoveryComponent {
  failed = false
  recoveryForm = this.formBuilder.group({
    uuid: ['', [Validators.compose([Validators.required, Validators.pattern(uuidPattern)])]]
  })

  constructor(private readonly formBuilder: FormBuilder,
              private readonly formService: SubmissionService,
              private readonly uiService: UIService,
              private readonly router: Router) {

  }

  submit() {
    this.failed = false
    const uuid = this.recoveryForm.getRawValue().uuid
    this.formService.getSubmission(uuid).pipe(
      first(),
      tap(() => {
        localStorage.setItem('submissionUUID', uuid)
        this.uiService.advanceToForm()
      }, (error) => {
        this.failed = true
        return genericErrorHandler(error, 'Failed to get submission')
      })
    ).subscribe()
  }
}

<app-info title="Recover Submission">
  <h4>If you've lost your submission and you've been redirected to this page; paste the key were you given below:</h4>
  <ng-container *ngIf="failed">
    <h4 class="error">Something went wrong</h4>
    <h4 class="error">Unable to recover submission, double check the key</h4>
  </ng-container>
  <div class="recovery-set" [formGroup]="recoveryForm">
    <input
      type="text"
      pInputText
      formControlName="uuid"
      placeholder="Paste key here">
    <p-button class="submit" [disabled]="!recoveryForm.valid" label="Submit" (click)="submit()"></p-button>
  </div>
</app-info>

// goty-client/src/components/Recovery.tsx
import React, { useEffect, useState } from 'react'
import { useStore } from 'react-redux'
import { useNavigate } from 'react-router-dom'
import styled from 'styled-components'
import { SubmissionService } from '../api/submissionService'
import { createNextStepAction } from '../state/submission/actions'
import { Card } from './Card'
import { TextInput } from './controls/TextInput'
import { Button } from './controls/Button'

const StyledContainer = styled.div`
  display: grid;
  grid-template-columns: 3fr 1fr;
`

const Error = styled.h4`
  color: #b00020;
`

const getFailed = () => (
  <>
    <Error>Something went wrong</Error>
    <Error>Unable to recover submission, double check the key</Error>
  </>
)

const uuidPattern =
  /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/

export const Recovery = () => {
  const store = useStore()
  const navigate = useNavigate()
  const [failed, setFailed] = useState(false)
  const [valid, setValid] = useState(false)
  const [uuid, setUuid] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  useEffect(() => {
    setFailed(false)
    setValid(uuidPattern.test(uuid))
  }, [uuid])
  useEffect(() => {
    document.title = 'TMW GOTY - Recovery'
  }, [])
  const handleSubmit = () => {
    setIsLoading(true)
    SubmissionService.getSubmission(uuid)
      .then(() => {
        localStorage.setItem('submissionUUID', uuid)
        store.dispatch(createNextStepAction())
        navigate('/submission')
      })
      .catch(() => {
        setIsLoading(false)
        setValid(false)
        setFailed(true)
      })
  }
  return (
    <Card title="Recover Submission">
      <h4>
        If you've lost your submission and you've been redirected to this page
        paste the key you were given below:
      </h4>
      {failed ? getFailed() : null}
      <StyledContainer>
        <TextInput
          id="recovery"
          value={uuid}
          onChange={setUuid}
          placeholder="Paste key here"
        />
        <Button
          disabled={!valid}
          label="Submit"
          onClick={handleSubmit}
          style={{ minWidth: '120px' }}
          loading={isLoading}
        />
      </StyledContainer>
    </Card>
  )
}
