// goty-client/src/components/submission/Giveaway.tsx
import React from 'react'
import { Card } from '../Card'

import { generateRules } from '../../util/generate-rules'
import { useSelector, useStore } from 'react-redux'
import { selectConstants } from '../../state/constants/selectors'
import { createUpdateEnteredGiveawayAction } from '../../state/submission/actions'
import { GotyRadioSet, RadioOption } from '../restyled/GotyRadioButton'

export interface GiveawayProps {
  readonly: boolean
  enteredGiveaway: boolean | null
}

const rules = (lastTime: string) => [
  'One entry per person',
  'The gift card will be given digitally through Steam',
  'You must have been a user of the TMW discord prior to the beginning of this contest',
  <li key="random">
    The winner will be revealed by screen recording the entries and rolling a
    random number on <a href="https://random.org">random.org</a>
  </li>,
  `Entries after ${lastTime} are void`,
  'The winner will be announced and prize distributed within a few days',
]

export const Giveaway = (props: GiveawayProps) => {
  const { lastTime, giveawayAmountUSD } = useSelector(selectConstants)
  const store = useStore()
  const handleClick = (enteredGiveaway: boolean) => {
    if (!props.readonly) {
      store.dispatch(createUpdateEnteredGiveawayAction(enteredGiveaway))
    }
  }
  const options: RadioOption[] = [
    {
      id: 'yes',
      value: true,
      label: 'Yes',
    },
    {
      id: 'no',
      value: false,
      label: 'No',
    },
  ]
  return (
    <Card title={`$${giveawayAmountUSD} Giveaway`} required={true}>
      {generateRules(props.readonly, rules(lastTime))}
      <GotyRadioSet
        disabled={props.readonly}
        name="giveaway"
        onChange={(e) => handleClick(e.value)}
        options={options}
        selectedValue={props.enteredGiveaway}
      />
    </Card>
  )
}

// goty-client/src/app/submission/giveaway/giveaway.component.ts
import {Component, Input} from '@angular/core'
import {constants} from 'src/api/constants'
import {SubmissionService} from '../../../api/submission/submission.service'

@Component({
  selector: 'app-giveaway',
  templateUrl: './giveaway.component.html',
  styleUrls: ['./giveaway.component.scss']
})
export class GiveawayComponent {
  @Input() enteredGiveaway
  @Input() readonly = false
  title = 'Giveaway'
  lastTime = constants.lastTime

  constructor(public readonly submissionService: SubmissionService) {
  }

  setEnteredGiveaway(enteredGiveaway: boolean) {
    if (!this.readonly) {
      this.submissionService.setEnteredGiveaway(enteredGiveaway)
    }
  }
}

<app-info [title]="title" [required]="true">
  <ng-container *ngIf="!readonly">
    <p>Rules:</p>
    <ul>
      <li>One entry per person</li>
      <li>The gift card will be given digitally through Steam</li>
      <li>You must have been a user of the TMW discord server prior to the beginning of this contest</li>
      <li>The winner will be revealed by screen recording the entries and rolling a random number on <a href="https://random.org">random.org</a></li>
      <li>Entries after {{lastTime}} are void</li>
      <li>The winner will be announced and prize distributed within a few days</li>
    </ul>
  </ng-container>
  <ng-container>
    <app-radio [ngModel]="enteredGiveaway" (ngModelChange)="giveawayChange.emit($event)" [readonly]="readonly"></app-radio>
  </ng-container>
</app-info>
